## Copy of scripts/plot_variance_popgroup_fixed.R using variance components estimated with the corrected G.
## =============================================================================
## 10 -- 100% stacked barplot of variance components (E, G, GxE, L, R) by
##        model (M1/M2/M3) and trait, matching the manuscript's Figure 2
##        format. Source: results/variance_components/variance_components.csv
##        (revised analysis, PopGroup fitted as a fixed effect throughout).
## =============================================================================

# Run from any directory: Rscript /path/to/scripts/plot_variance_popgroup_fixed.R
script_arg <- grep("^--file=", commandArgs(), value = TRUE)
source_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
script_file <- if (!is.null(source_file)) source_file else if (length(script_arg))
  gsub("~+~", " ", sub("^--file=", "", script_arg[1]), fixed = TRUE) else NULL
root <- if (!is.null(script_file)) dirname(dirname(normalizePath(script_file))) else
  if (basename(getwd()) == "scripts") dirname(getwd()) else getwd()
root <- dirname(root)  # project root (script lives in reviewer_FW_MC_pipeline/scripts)
outdir <- file.path(root, "reviewer_FW_MC_pipeline", "results", "corrected_G", "variance_components", "figure")
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

suppressMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
})

vc <- read.csv(file.path(root, "reviewer_FW_MC_pipeline/results/corrected_G/variance_components/variance_components.csv"), stringsAsFactors = FALSE)

required <- c("sigma2_E", "sigma2_L", "sigma2_G", "sigma2_GxE", "sigma2_e")
stopifnot(nrow(vc) == 9, !anyDuplicated(vc[c("trait", "model")]),
          setequal(vc$trait, c("DM", "FW", "MC")),
          setequal(vc$model, c("M1", "M2", "M3")))
for (i in seq_len(nrow(vc))) {
  active <- c("sigma2_E", "sigma2_L", "sigma2_e",
              if (vc$model[i] != "M1") "sigma2_G",
              if (vc$model[i] == "M3") "sigma2_GxE")
  values <- unlist(vc[i, active])
  stopifnot(all(is.finite(values)), all(values >= 0), sum(values) > 0)
}
# Match script 09's component-parameter normalization; kernels are unscaled.
# Fixed PopGroup has no random variance parameter, so no PopGroup segment.
long <- vc |>
  select(trait, model, E = sigma2_E, G = sigma2_G, GxE = sigma2_GxE,
         L = sigma2_L, R = sigma2_e) |>
  pivot_longer(cols = c(E, G, GxE, L, R), names_to = "component", values_to = "variance") |>
  filter(!is.na(variance)) |>
  group_by(trait, model) |>
  mutate(pct = 100 * variance / sum(variance)) |>
  ungroup()

long$trait <- factor(long$trait, levels = c("DM", "FW", "MC"))
long$model <- factor(long$model, levels = c("M1", "M2", "M3"))
long$component <- factor(long$component, levels = c("R", "L", "G", "GxE", "E"))

long <- long |>
  arrange(trait, model, component) |>
  group_by(trait, model) |>
  mutate(ymax = pmin(cumsum(pct), 100), ymin = pmax(ymax - pct, 0)) |>
  ungroup()

w <- 0.35
long$xnum <- as.numeric(long$model)

p <- ggplot(long) +
  geom_rect(aes(xmin = xnum - w, xmax = xnum + w, ymin = ymin, ymax = ymax, fill = component),
            colour = "white", linewidth = 0.3) +
  scale_x_continuous(breaks = 1:3, labels = c("M1", "M2", "M3")) +
  facet_wrap(~ trait, nrow = 1) +
  scale_fill_manual(
    values = c(E = "#F4867A", G = "#9B9B2E", GxE = "#4CAF6D", L = "#4FA3D9", R = "#E066D6"),
    breaks = c("E", "G", "GxE", "L", "R"),
    name = "Variance component"
  ) +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0)) +
  labs(x = NULL, y = "Percentage variance") +
  theme_bw(base_size = 11) +
  theme(strip.background = element_rect(fill = "grey85"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())

stopifnot(all(abs(tapply(long$pct, interaction(long$trait, long$model), sum) - 100) < 1e-8))
write.csv(long, file.path(outdir, "variance_percentages.csv"), row.names = FALSE)
ggsave(file.path(outdir, "variance_components_popgroup_fixed.png"), p,
       width = 8.5, height = 4.5, dpi = 300, bg = "white")
ggsave(file.path(outdir, "variance_components_popgroup_fixed.pdf"), p,
       width = 8.5, height = 4.5, bg = "white")
writeLines(c(
  "Source: ../variance_components.csv, generated by scripts/09_variance_components.R.",
  "M1/M2/M3 include PopGroup as a fixed effect (BGLR FIXED term).",
  "Bars normalize mean variance-component estimates across five runs to 100%.",
  "E: environment; G: genomic; GxE: genomic-by-environment; L: line; R: residual.",
  "PopGroup has no random variance component and is not a bar segment.",
  "These percentages follow script 09's unscaled-kernel convention; they are component-parameter shares.",
  "Existing fitted results were reused; no models were refitted for this plot."
), file.path(outdir, "figure_notes.txt"))
cat("Saved PNG, PDF and plotted percentages in", outdir, "\n")
